FROM phgasnets-dev

ARG PROJECT_DIR=/phgasnets/src
ARG BUILD_DIR=/phgasnets/build
ARG OUT_DIR=/phgasnets/run

USER root

COPY . ${PROJECT_DIR}

RUN cmake -B ${BUILD_DIR} -S ${PROJECT_DIR} -DCMAKE_BUILD_TYPE=Release && cmake --build ${BUILD_DIR} --parallel && chmod +x ${PROJECT_DIR}/RUNME.sh

VOLUME ${OUT_DIR}

ENV PROJECT_DIR ${PROJECT_DIR}
ENV BUILD_DIR ${BUILD_DIR}
ENV OUT_DIR ${OUT_DIR}

CMD ${PROJECT_DIR}/RUNME.sh
